Deploy-Production-SonoranRadioFiveMResource:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - cp -rf static/ build/sonoranradio/
    - cp -rf lua/ build/sonoranradio/
    - mkdir -p build/sonoranradio/dist
    - cp -rf dist/bundle.js build/sonoranradio/dist/bundle.js
    - cp -rf dist/bundle.css build/sonoranradio/dist/bundle.css
    - cp -rf dist/ui.html build/sonoranradio/dist/ui.html
    - cd build
    - zip -r latest sonoranradio
    - zip -r latest sonoranradio_updatehelper
    - mv latest.zip ../latest.zip
    - cd ..
    - rsync latest.zip git@172.107.228.131:/home/services/frontend/www/download.sonoransoftware.com/sonoranradio/archive/latest.zip
    - rsync version.json git@172.107.228.131:/home/services/frontend/www/download.sonoransoftware.com/sonoranradio/version.json
  tags:
    - linux, build, shell, development
  only:
    - master